#name: Auto-Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install --upgrade pip
      - run: pip install -Ur requirements.txt
      - run: pip list --outdated
        if: (env.ACT)
      - run: mkdocs build --site-dir public
      - uses: actions/upload-pages-artifact@v3
        if: (!env.ACT)
        with:
          path: public/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
#    permissions:
#      pages: write
#      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
